export const TARGET_RTP: number;
export const CORE_RTP: number;
export const MAX_SETTLEMENT_MULTIPLIER: number;
export const PUMPKIN_MIN_TARGET: number;

export type RtpRoleId = "potato" | "chili" | "pumpkin" | "tomato" | "pepper" | "mushroom";
export type AbilityRolls = number | Partial<Record<RtpRoleId | "target" | "dashPrize", number>>;
export type SettlementResult = { payout: number; note: string; outcome: "neutral" | "bonus"; triggeredRoleIds: RtpRoleId[]; bonusDistance: number };
export type RtpWager = { roleId: RtpRoleId; stake: number; target: number; manual?: boolean; duoFactor?: number };
export type CrashCurve = { openingSurvival: number; exponent: number };
export type PumpkinContract = { active: boolean; stake: number; target: number; clears: number; multipliers: number[]; stages: number; factor: number; expectedFactor: number; ruleKey: string; baseRtp: number; crashCurve: CrashCurve; poolAssisted: boolean; poolReserved: number };
export type PumpkinSettlement = { accepted: boolean; complete: boolean; payout: number; contract: PumpkinContract };
export type DuoDescription = { key: string; title: string; badge: string; shortSummary: string; summary: string; roleDetails: string[] };
export type VisualNearMiss = { active: true; extended: boolean; cashAt: number; naturalEnd: number; visualEnd: number };
export type DuoRule = { title: string; kind: "chance" | "auto" | "dash" | "contract"; summary: string; chance?: number; factor?: number; baseFactor?: number; bonusDistance?: number; min?: number; max?: number; autoMin?: number; autoMax?: number; stages?: number; targetMode?: "selected" | "fixed" | "auto"; target?: number };
export type DuoRuntime = { key: string; rule: DuoRule; factor: number; expectedFactor: number; bonusDistance: number; expectedBonusDistance: number; autoTarget: number | null; contractTarget: number | null };

export const ROLE_MATH: Readonly<Record<RtpRoleId, Readonly<Record<string, number>>>>;
export const ROLE_NAMES: Readonly<Record<RtpRoleId, string>>;
export const DASH_DISTANCES: readonly number[];
export const DUO_RULES: Readonly<Record<string, Readonly<DuoRule>>>;
export function duoRuleFor(roleIds: RtpRoleId[]): DuoRule | null;
export function duoRuntimeFromRolls(roleIds: RtpRoleId[], rolls?: AbilityRolls): DuoRuntime | null;
export function duoRuntimeForTicket(roleIds: RtpRoleId[], ticketRolls: AbilityRolls[], ticketIndex?: number): DuoRuntime | null;
export function describeDuoPair(roleIds: RtpRoleId[]): DuoDescription;
export function crashPointFromUnit(unit: number, baseRtp?: number): number;
export function survivalAt(multiplier: number, baseRtp?: number): number;
export function defaultCrashCurve(): CrashCurve;
export function crashPointFromCurveUnit(unit: number, curve?: CrashCurve): number;
export function survivalAtCurve(multiplier: number, curve?: CrashCurve): number;
export function createVisualNearMiss(cashAt: number, naturalEnd: number, unit: number): VisualNearMiss;
export function dashDistanceFromUnit(unit: number): number;
export function createPumpkinContract(stake: number, target: number, options?: { stages?: number; factor?: number; expectedFactor?: number; ruleKey?: string }): PumpkinContract;
export function settlePumpkinCashout(contract: PumpkinContract, multiplier: number): PumpkinSettlement;
export function settlePumpkinCrash(contract: PumpkinContract): PumpkinContract;
export function pumpkinContractBaseRtp(target: number, options?: { stages?: number; factor?: number; expectedFactor?: number }): number;
export function expectedPumpkinContractReturn(stake: number, target: number, baseRtp: number, options?: { stages?: number; factor?: number; expectedFactor?: number }): number;
export function calibratePumpkinContracts(contracts: PumpkinContract[]): number;
export function expectedPumpkinContractReturnForCurve(stake: number, target: number, curve: CrashCurve, options?: { stages?: number; factor?: number; expectedFactor?: number }): number;
export function calibratePumpkinCrashCurve(contracts: PumpkinContract[]): CrashCurve;
export function settleSuccessfulCashout(roleId: RtpRoleId, stake: number, multiplier: number, rolls: AbilityRolls, roundRoleIds?: RtpRoleId[], options?: { duoRuntime?: DuoRuntime }): SettlementResult;
export function settleCrashRole(roleId: RtpRoleId, stake: number, crashPoint: number, rolls: AbilityRolls, roundRoleIds?: RtpRoleId[]): SettlementResult;
export function expectedSuccessfulPayout(roleId: RtpRoleId, stake: number, multiplier: number, roundRoleIds?: RtpRoleId[], options?: { duoFactor?: number; duoRuntime?: DuoRuntime }): number;
export function expectedCrashPayout(roleId: RtpRoleId, stake: number, crashPoint: number, roundRoleIds?: RtpRoleId[]): number;
export function expectedRoundReturn(wagers: RtpWager[], baseRtp: number): number;
export function calibrateRoundBaseRtp(wagers: RtpWager[]): number;
export function expectedRoundReturnForCurve(wagers: RtpWager[], curve: CrashCurve): number;
export function calibrateRoundCrashCurve(wagers: RtpWager[]): CrashCurve;
