export const TARGET_RTP: number;
export const MAX_SETTLEMENT_MULTIPLIER: number;

export type RtpRoleId = "potato" | "chili" | "pumpkin" | "tomato" | "peapod" | "mushroom";
export type SupportId = "ketchup" | "mayonnaise" | "mustard" | "wasabi";
export type AbilityRolls = number | Partial<Record<RtpRoleId, number>>;
export type SettlementResult = { payout: number; note: string; outcome: "neutral" | "bonus"; triggeredRoleIds: RtpRoleId[] };
export type RtpWager = { roleId: RtpRoleId; stake: number; target: number };
export type DuoTicket = { roleId: RtpRoleId; stake: number; cashAt: number | null; payout: number; status: string; placed?: boolean; linkAwarded?: boolean };
export type DuoDescription = { key: string; title: string; badge: string; shortSummary: string; summary: string; roleDetails: string[] };
export type DuoSettlement = { extras: number[]; total: number; note: string; triggered: boolean; description: DuoDescription | null };
export type SupportWager = { stake: number; target: number };
export type VisualNearMiss = { active: true; extended: boolean; cashAt: number; naturalEnd: number; visualEnd: number };

export const ROLE_MATH: Readonly<Record<RtpRoleId, Readonly<Record<string, number>>>>;
export const ROLE_NAMES: Readonly<Record<RtpRoleId, string>>;
export const SUPPORT_MATH: Readonly<Record<SupportId, Readonly<Record<string, number>>>>;
export const SUPPORT_NAMES: Readonly<Record<SupportId, string>>;
export function describeDuoPair(roleIds: RtpRoleId[]): DuoDescription;
export function crashPointFromUnit(unit: number, baseRtp?: number): number;
export function survivalAt(multiplier: number, baseRtp?: number): number;
export function createVisualNearMiss(cashAt: number, naturalEnd: number, unit: number): VisualNearMiss;
export function settleSuccessfulCashout(roleId: RtpRoleId, stake: number, multiplier: number, rolls: AbilityRolls, roundRoleIds?: RtpRoleId[]): SettlementResult;
export function settleCrashRole(): SettlementResult;
export function settleDuoLink(tickets: DuoTicket[]): DuoSettlement;
export function settleSupportLink(tickets: DuoTicket[], supportId: SupportId): DuoSettlement;
export function expectedSuccessfulPayout(roleId: RtpRoleId, stake: number, multiplier: number, roundRoleIds?: RtpRoleId[]): number;
export function expectedCrashPayout(): number;
export function expectedRoundReturn(wagers: RtpWager[], baseRtp: number): number;
export function calibrateRoundBaseRtp(wagers: RtpWager[]): number;
export function expectedSupportRoundReturn(mainWager: RtpWager | null, supportWager: SupportWager | null, supportId: SupportId, baseRtp: number): number;
export function calibrateSupportRoundBaseRtp(mainWager: RtpWager | null, supportWager: SupportWager | null, supportId: SupportId): number;
