export const TARGET_RTP: number;
export const MAX_SETTLEMENT_MULTIPLIER: number;

export type RtpRoleId = "potato" | "chili" | "pumpkin" | "tomato" | "peapod" | "mushroom";
export type AbilityRolls = number | Partial<Record<RtpRoleId | "target" | "peapodTarget" | "peapodPrize", number>>;
export type SettlementResult = { payout: number; note: string; outcome: "neutral" | "bonus"; triggeredRoleIds: RtpRoleId[] };
export type RtpWager = { roleId: RtpRoleId; stake: number; target: number; manual?: boolean; peapodThreshold?: number; peapodFactor?: number; duoThreshold?: number; duoFactor?: number };
export type PumpkinContract = { active: boolean; stake: number; target: number; clears: number; multipliers: number[]; stages: number; factor: number; ruleKey: string; baseRtp: number };
export type PumpkinSettlement = { accepted: boolean; complete: boolean; payout: number; contract: PumpkinContract };
export type DuoDescription = { key: string; title: string; badge: string; shortSummary: string; summary: string; roleDetails: string[] };
export type VisualNearMiss = { active: true; extended: boolean; cashAt: number; naturalEnd: number; visualEnd: number };
export type DuoRule = { title: string; kind: "chance" | "auto" | "reveal" | "reveal-auto" | "contract"; summary: string; chance?: number; factor?: number; min?: number; max?: number; autoMin?: number; autoMax?: number; thresholds?: number[]; prizeProfile?: string; stages?: number; targetMode?: "selected" | "fixed" | "auto" | "reveal"; target?: number };
export type DuoRuntime = { key: string; rule: DuoRule; threshold: number; factor: number; autoTarget: number | null; contractTarget: number | null };

export const ROLE_MATH: Readonly<Record<RtpRoleId, Readonly<Record<string, number>>>>;
export const ROLE_NAMES: Readonly<Record<RtpRoleId, string>>;
export const PEAPOD_THRESHOLDS: readonly number[];
export const DUO_RULES: Readonly<Record<string, Readonly<DuoRule>>>;
export function duoRuleFor(roleIds: RtpRoleId[]): DuoRule | null;
export function duoRuntimeFromRolls(roleIds: RtpRoleId[], rolls?: AbilityRolls): DuoRuntime | null;
export function duoRuntimeForTicket(roleIds: RtpRoleId[], ticketRolls: AbilityRolls[], ticketIndex?: number): DuoRuntime | null;
export function describeDuoPair(roleIds: RtpRoleId[]): DuoDescription;
export function crashPointFromUnit(unit: number, baseRtp?: number): number;
export function survivalAt(multiplier: number, baseRtp?: number): number;
export function createVisualNearMiss(cashAt: number, naturalEnd: number, unit: number): VisualNearMiss;
export function peapodThresholdFromUnit(unit: number): number;
export function peapodPayoutFactorFromUnit(unit: number): number;
export function createPumpkinContract(stake: number, target: number, options?: { stages?: number; factor?: number; ruleKey?: string }): PumpkinContract;
export function settlePumpkinCashout(contract: PumpkinContract, multiplier: number): PumpkinSettlement;
export function settlePumpkinCrash(contract: PumpkinContract): PumpkinContract;
export function pumpkinContractBaseRtp(target: number, options?: { stages?: number; factor?: number }): number;
export function expectedPumpkinContractReturn(stake: number, target: number, baseRtp: number, options?: { stages?: number; factor?: number }): number;
export function calibratePumpkinContracts(contracts: PumpkinContract[]): number;
export function settleSuccessfulCashout(roleId: RtpRoleId, stake: number, multiplier: number, rolls: AbilityRolls, roundRoleIds?: RtpRoleId[], options?: { peapodThreshold?: number; peapodFactor?: number; duoRuntime?: DuoRuntime }): SettlementResult;
export function settleCrashRole(roleId: RtpRoleId, stake: number, crashPoint: number, rolls: AbilityRolls, roundRoleIds?: RtpRoleId[]): SettlementResult;
export function expectedSuccessfulPayout(roleId: RtpRoleId, stake: number, multiplier: number, roundRoleIds?: RtpRoleId[], options?: { peapodThreshold?: number; peapodFactor?: number; duoThreshold?: number; duoFactor?: number; duoRuntime?: DuoRuntime }): number;
export function expectedCrashPayout(roleId: RtpRoleId, stake: number, crashPoint: number, roundRoleIds?: RtpRoleId[]): number;
export function expectedRoundReturn(wagers: RtpWager[], baseRtp: number): number;
export function calibrateRoundBaseRtp(wagers: RtpWager[]): number;
